#!/bin/bash

# Copyright (C) 2017-2019 Andrei Pavel, andrei.pavel@cti.pub.ro
# Licensed under the MIT License

# Header
ARGUMENTS="\
  [-p|--prefix] \$prefix        sets the \${pkgdir} used for AUR PKGBUILD
"
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

# Parse arguments.
pkgdir=
while (( ${#} > 0 )); do
  case "${1}" in
  # [-p|--prefix] \$prefix        sets the \${pkgdir} used for AUR PKGBUILD
  '-p'|'--prefix') shift && pkgdir="${1}";;
  *)
    # Unrecognized argument
    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; print-usage; exit 1;;
  esac; shift
done

#------------------------------------------------------------------------------#

pushd "${SCRIPT_PATH}" > /dev/null
{
  diff './fetch-replici.net' "${pkgdir}/usr/local/bin/fetch-replici.net"
  diff './share/Caddyfile' '/etc/caddy/Caddyfile'
  diff './share/caddy.service' "${pkgdir}/lib/systemd/system/caddy.service"
  diff './share/fetch-replici.net.service' "${pkgdir}/lib/systemd/system/fetch-replici.net.service"
  diff './share/podcasts-Caddyfile' '/etc/fetch-replici.net/Caddyfile'
  diff './share/privacy-policy.html' '/usr/share/replici.net/privacy-policy.html'
}
popd 1> /dev/null
